version: "3"
services:
    papa:
        build: src/backend/pa
        restart: always
        depends_on:
            - mice
    mice:
        build: src/backend/mouse
        restart: always
        depends_on:
            - monitor
    friends:
        build: src/backend/friends
        restart: always
        depends_on:
            - monitor
    monitor:
        build: src/backend/monitor
        restart: always
        depends_on:
            - db
        ports: 
            - "8080:8080"
    db:
        environment:
            MYSQL_DATABASE: candy
            MYSQL_ROOT_PASSWORD: init1234
            MYSQL_USER: gocli
            MYSQL_PASSWORD: init1234
        build: .
       #image: mysql/mysql-server:latest 
        restart: always
        ports: 
            - "3306:3306"
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=init1234 --execute \"SHOW DATABASES;\""
            timeout: 20s
            retries: 10
