version: "3"
services:
    db:
        environment:
            MYSQL_DATABASE: candy
            MYSQL_ROOT_PASSWORD: init1234
            MYSQL_USER: gocli
            MYSQL_PASSWORD: init1234
        build: .
       #image: mysql/mysql-server:latest 
        restart: always
