version: "3"
services:
    mice:
        build: src/backend/mouse
        restart: always
        depends_on:
            - db
    friends:
        build: src/backend/friends
        restart: always
        depends_on:
            - db
    monitor:
        build: src/backend/monitor
        restart: always
        depends_on:
            - db
    db:
        environment:
            MYSQL_DATABASE: candy
            MYSQL_ROOT_PASSWORD: init1234
            MYSQL_USER: gocli
            MYSQL_PASSWORD: init1234
        build: .
       #image: mysql/mysql-server:latest 
        restart: always
        expose: 
            - "3306"
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=init1234 --execute \"SHOW DATABASES;\""
            timeout: 20s
            retries: 10
